name: M3CoTBench_env
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=3_kmp_llvm
  - bzip2=1.0.8=h4bc722e_7
  - c-ares=1.34.5=hb9d3cd8_0
  - ca-certificates=2025.7.14=hbd8a1cb_0
  - icu=75.1=he02047a_0
  - kernel-headers_linux-64=3.10.0=he073ed8_18
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.21.3=h659f571_0
  - ld_impl_linux-64=2.44=h1423503_1
  - libcurl=8.14.1=h332b0f4_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libev=4.33=hd590300_2
  - libexpat=2.7.1=hecca717_0
  - libffi=3.4.6=h2dba641_1
  - libgcc=15.1.0=h767d61c_3
  - libgcc-ng=15.1.0=h69a702a_3
  - libgomp=15.1.0=h767d61c_3
  - libhwloc=2.11.2=default_h3d81e11_1002
  - libiconv=1.18=h4ce23a2_1
  - liblzma=5.8.1=hb9d3cd8_2
  - libnghttp2=1.64.0=h161d5f1_0
  - libnsl=2.0.1=hb9d3cd8_1
  - libpython-static=3.10.18=h5888daf_0_cpython
  - libsqlite=3.50.3=hee844dc_0
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.1.0=h8f9b012_3
  - libstdcxx-ng=12.3.0=hc0a3c3a_7
  - libuuid=2.38.1=h0b41bf4_0
  - libuv=1.51.0=hb9d3cd8_0
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.13.8=h4bc477f_0
  - libzlib=1.3.1=hb9d3cd8_2
  - llvm-openmp=20.1.8=h4922eb0_0
  - llvmdev=8.0.0=hc9558a2_2
  - mkl=2021.4.0=h8d4b97c_729
  - mkl-include=2021.4.0=h8d4b97c_729
  - ncurses=6.5=h2d0b736_3
  - openssl=3.5.1=h7b32b05_0
  - python=3.10.18=hd6af730_0_cpython
  - readline=8.2=h8c095d6_2
  - rhash=1.4.6=hb9d3cd8_1
  - setuptools=80.9.0=pyhff2d567_0
  - sqlite=3.50.3=heff268d_0
  - sysroot_linux-64=2.17=h0157908_18
  - tbb=2021.13.0=hceb3a55_1
  - tk=8.6.13=noxft_hd72426e_102
  - wheel=0.45.1=pyhd8ed1ab_1
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
      - absl-py==2.3.1
      - accelerate==1.9.0
      - aiofiles==24.1.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.14
      - aiosignal==1.4.0
      - alembic==1.16.5
      - altair==5.5.0
      - amdsmi==25.5.1+41065ee6
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.10.0
      - apex==1.7.0a0
      - argparse==1.4.0
      - asttokens==3.0.0
      - astunparse==1.6.3
      - async-timeout==5.0.1
      - attrs==25.3.0
      - audioread==3.0.1
      - av==15.1.0
      - blinker==1.9.0
      - blobfile==3.0.0
      - boto3==1.35.42
      - botocore==1.35.99
      - brotli==1.1.0
      - cachetools==5.5.2
      - certifi==2025.7.14
      - cffi==1.17.1
      - charset-normalizer==3.4.2
      - click==8.1.8
      - cloudpickle==3.1.1
      - cmake==3.31.0
      - colorama==0.4.6
      - coloredlogs==15.0.1
      - contourpy==1.3.2
      - coremltools==5.0b5
      - cos-python-sdk-v5==1.9.38
      - coscmd==1.9.0.6
      - crcmod==1.7
      - cryptography==45.0.5
      - cxxfilt==0.3.0
      - cycler==0.12.1
      - databricks-sdk==0.65.0
      - datasets==4.0.0
      - datetime==5.5
      - decorator==5.2.1
      - decord==0.6.0
      - deepspeed==0.17.4
      - deprecated==1.2.18
      - diffsynth==1.1.8
      - diffusers==0.35.1
      - dill==0.3.8
      - docker==7.1.0
      - docstring-parser==0.17.0
      - easydict==1.13
      - einops==0.8.1
      - et-xmlfile==2.0.0
      - exceptiongroup==1.3.0
      - execnet==2.1.1
      - executing==2.2.0
      - expecttest==0.2.1
      - fastapi==0.116.1
      - fbscribelogger==0.1.7
      - ffmpy==0.6.1
      - filelock==3.18.0
      - fire==0.7.0
      - flash-attn==3.0.0.post1
      - flask==3.1.2
      - flatbuffers==2.0
      - fonttools==4.59.0
      - frozenlist==1.7.0
      - fsspec==2025.3.0
      - ftfy==6.3.1
      - future==1.0.0
      - gevent==25.8.2
      - ghstack==0.8.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - google-auth==2.40.3
      - google-auth-oauthlib==1.0.0
      - gradio==5.45.0
      - gradio-client==1.13.0
      - graphene==3.4.3
      - graphql-core==3.2.6
      - graphql-relay==3.2.0
      - greenlet==3.2.4
      - groovy==0.1.2
      - grouped-gemm==1.1.4
      - grpcio==1.73.1
      - gunicorn==23.0.0
      - h11==0.16.0
      - hf-transfer==0.1.9
      - hf-xet==1.1.7
      - hiredis==3.2.1
      - hjson==3.1.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.34.4
      - humanfriendly==10.0
      - hypothesis==5.35.1
      - idna==3.10
      - imageio==2.37.0
      - imageio-ffmpeg==0.6.0
      - importlib-metadata==8.7.0
      - importlib-resources==6.5.2
      - iniconfig==2.1.0
      - ipython==8.37.0
      - itsdangerous==2.2.0
      - jedi==0.19.2
      - jinja2==3.1.4
      - jmespath==1.0.1
      - joblib==1.5.1
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - junitparser==2.1.1
      - kagglehub==0.3.12
      - kiwisolver==1.4.9
      - kornia==0.8.1
      - kornia-rs==0.1.9
      - lark==0.12.0
      - lazy-loader==0.4
      - librosa==0.11.0
      - lintrunner==0.12.5
      - llvmlite==0.44.0
      - lmdb==1.7.3
      - lxml==5.3.0
      - mako==1.3.10
      - markdown==3.8.2
      - markdown-it-py==4.0.0
      - markupsafe==3.0.2
      - matplotlib==3.10.5
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - ml-dtypes==0.5.1
      - mlflow==3.3.2
      - mlflow-skinny==3.3.2
      - mlflow-tracing==3.3.2
      - modelscope==1.30.0
      - moviepy==2.2.1
      - mpmath==1.3.0
      - msgpack==1.1.1
      - multidict==6.6.3
      - multiprocess==0.70.16
      - mypy==1.13.0
      - mypy-extensions==1.1.0
      - narwhals==2.4.0
      - networkx==2.8.8
      - nibabel==5.3.2
      - ninja==1.13.0
      - numba==0.61.2
      - numpy==1.26.4
      - nvidia-ml-py==13.580.82
      - oauthlib==3.3.1
      - omegaconf==2.3.0
      - onnx==1.16.1
      - onnxruntime==1.22.1
      - onnxscript==0.1.0.dev20240817
      - opencv-python-headless==4.10.0.84
      - openpyxl==3.1.5
      - opentelemetry-api==1.36.0
      - opentelemetry-sdk==1.36.0
      - opentelemetry-semantic-conventions==0.57b0
      - opt-einsum==3.3.0
      - optree==0.17.0
      - orjson==3.11.1
      - packaging==25.0
      - pandas==2.2.3
      - parallel-ssh==2.14.0
      - parameterized==0.8.1
      - parso==0.8.4
      - peft==0.17.0
      - pexpect==4.9.0
      - pillow==11.0.0
      - pip==25.2
      - platformdirs==4.3.8
      - pluggy==1.6.0
      - ply==3.11
      - pooch==1.8.2
      - prettytable==3.16.0
      - proglog==0.1.12
      - prompt-toolkit==3.0.51
      - propcache==0.3.2
      - protobuf==3.20.2
      - pssh==2.3.1
      - psutil==7.0.0
      - ptyprocess==0.7.0
      - pulp==2.9.0
      - pure-eval==0.2.3
      - pwlf==2.2.1
      - py-cpuinfo==9.0.0
      - pyarrow==21.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pybind11==3.0.0
      - pycparser==2.22
      - pycryptodome==3.23.0
      - pycryptodomex==3.23.0
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - pydeck==0.9.1
      - pydoe==0.3.8
      - pydub==0.25.1
      - pygithub==2.3.0
      - pygments==2.15.0
      - pyjwt==2.10.1
      - pynacl==1.5.0
      - pynvml==13.0.1
      - pyparsing==3.2.3
      - pytest==7.3.2
      - pytest-cpp==2.3.0
      - pytest-flakefinder==1.1.0
      - pytest-rerunfailures==10.3
      - pytest-subtests==0.13.1
      - pytest-xdist==3.3.1
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.1.1
      - python-multipart==0.0.20
      - pytz==2025.2
      - pywavelets==1.4.1
      - pyyaml==6.0.2
      - qwen-vl-utils==0.0.14
      - redis==4.0.0
      - referencing==0.36.2
      - regex==2025.7.34
      - requests==2.32.4
      - requests-oauthlib==2.0.0
      - rich==14.1.0
      - rpds-py==0.27.1
      - rsa==4.9.1
      - ruff==0.13.0
      - s3transfer==0.10.4
      - safehttpx==0.1.6
      - safetensors==0.6.2
      - scikit-image==0.22.0
      - scikit-learn==1.7.1
      - scikit-video==1.1.11
      - scipy==1.14.1
      - semantic-version==2.10.0
      - sentencepiece==0.2.0
      - sentry-sdk==2.34.1
      - shellingham==1.5.4
      - shtab==1.7.2
      - simplejson==3.20.1
      - six==1.17.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - sortedcontainers==2.4.0
      - soundfile==0.13.1
      - soxr==0.5.0.post1
      - sqlalchemy==2.0.43
      - sqlparse==0.5.3
      - ssh-python==1.1.1
      - ssh2-python==1.1.2.post1
      - stack-data==0.6.3
      - starlette==0.47.3
      - streamlit==1.49.1
      - sympy==1.14.0
      - tabulate==0.9.0
      - tb-nightly==2.13.0a20230426
      - tenacity==9.1.2
      - tensorboard==2.18.0
      - tensorboard-data-server==0.7.2
      - tensorboardx==2.6.4
      - termcolor==3.1.0
      - threadpoolctl==3.6.0
      - thriftpy2==0.5.3
      - tifffile==2025.5.10
      - tiktoken==0.11.0
      - timm==1.0.19
      - tlparse==0.3.25
      - tokenizers==0.22.1
      - toml==0.10.2
      - tomli==2.2.1
      - tomlkit==0.13.3
      - torch==2.8.0a0+gitd06a406
      - torchao==0.13.0+git262b180ce
      - torchdata==0.11.0
      - torchtitan==0.0.2
      - torchtune==0.0.0
      - torchvision==0.22.0a0+5f03dc5
      - tornado==6.5.2
      - tqdm==4.67.1
      - traitlets==5.14.3
      - transformer-engine==2.2.0.dev0+94e53dd8
      - transformers==4.57.1
      - triton==3.3.0
      - trl==0.21.0
      - typeguard==4.4.4
      - typer==0.17.4
      - typing-extensions==4.14.1
      - typing-inspection==0.4.1
      - tyro==0.9.28
      - tzdata==2025.2
      - ujson==5.10.0
      - unittest-xml-reporting==3.2.0
      - urllib3==2.5.0
      - uv==0.8.8
      - uvicorn==0.35.0
      - wandb==0.21.1
      - watchdog==6.0.0
      - wcwidth==0.2.13
      - websockets==15.0.1
      - werkzeug==3.1.3
      - wrapt==1.17.2
      - xdoctest==1.1.0
      - xmltodict==0.15.1
      - xxhash==3.5.0
      - yappi==1.6.10
      - yarl==1.20.1
      - z3-solver==4.12.2.0
      - zipp==3.23.0
      - zope-event==5.1.1
      - zope-interface==7.2
